// Pulls the live catalog from Shopify Storefront API and writes
// src/data/shopify-catalog.ts. No token? Keeps the demo catalog untouched.
// Usage: SHOPIFY_STORE_DOMAIN=x.myshopify.com SHOPIFY_STOREFRONT_TOKEN=shpsa_... node scripts/sync-shopify.mjs
import { writeFileSync, existsSync } from "node:fs";

const domain = process.env.SHOPIFY_STORE_DOMAIN;
const token = process.env.SHOPIFY_STOREFRONT_TOKEN;
const out = new URL("../src/data/shopify-catalog.ts", import.meta.url);

if (!domain || !token) {
  console.log("sync-shopify: no SHOPIFY_STORE_DOMAIN/TOKEN — keeping demo catalog.");
  process.exit(0);
}

const query = `{
  products(first: 100) {
    nodes {
      handle title vendor tags
      description(truncateAt: 220)
      featuredImage { url altText }
      priceRange { minVariantPrice { amount } }
      compareAtPriceRange { minVariantPrice { amount } }
      variants(first: 1) { nodes { id sku } }
      metafields(identifiers: [
        {namespace:"custom",key:"publisher"},{namespace:"custom",key:"pages"},
        {namespace:"custom",key:"language"},{namespace:"custom",key:"edition"},
        {namespace:"custom",key:"genre"},
        {namespace:"reviews",key:"rating"},{namespace:"reviews",key:"rating_count"}
      ]) { key value }
    }
  }
}`;

const res = await fetch(`https://${domain}/api/2026-01/graphql.json`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "X-Shopify-Storefront-Access-Token": token,
  },
  body: JSON.stringify({ query }),
});
if (!res.ok) {
  console.error(`sync-shopify: HTTP ${res.status} — keeping demo catalog.`);
  process.exit(0);
}
const json = await res.json();
if (json.errors) {
  console.error("sync-shopify:", JSON.stringify(json.errors).slice(0, 300));
  process.exit(0);
}

const MOODS = ["feel", "thrill", "learn", "reflect", "love", "grow", "escape", "light"];
const CATS = ["fiction", "mystery-thriller", "self-help", "hindi-literature", "english-literature", "biography-history", "children", "education-exams", "maths-science"];

const books = (json.data?.products?.nodes ?? []).map((p) => {
  const tags = (p.tags ?? []).map((t) => t.toLowerCase());
  const mf = Object.fromEntries((p.metafields ?? []).filter(Boolean).map((m) => [m.key, m.value]));
  const price = Math.round(parseFloat(p.priceRange?.minVariantPrice?.amount ?? "0"));
  const mrpRaw = parseFloat(p.compareAtPriceRange?.minVariantPrice?.amount ?? "0");
  const pick = (list) => list.filter((x) => tags.includes(x));
  const isNew = tags.includes("newarrival") || tags.includes("new");
  return {
    slug: p.handle,
    title: p.title,
    author: p.vendor || "Aapki Kitab",
    isbn: p.variants?.nodes?.[0]?.sku ?? null,
    publisher: mf.publisher ?? "",
    pages: parseInt(mf.pages ?? "0", 10) || 0,
    language: mf.language ?? "English",
    edition: mf.edition ?? "",
    genre: mf.genre ?? "",
    price,
    mrp: mrpRaw > price ? Math.round(mrpRaw) : price,
    // Real ratings only: written by a Shopify review app into the standard reviews.* metafields.
    rating: (() => { try { return parseFloat(JSON.parse(mf.rating ?? "{}").value ?? "0") || 0; } catch { return 0; } })(),
    reviews: parseInt(mf.rating_count ?? "0", 10) || 0,
    cover: p.featuredImage?.url ?? null,
    coverTint: "#4b0f8a",
    moods: pick(MOODS),
    exams: tags.filter((t) => !MOODS.includes(t) && !CATS.includes(t) && !["newarrival", "new", "bestseller", "featured", "trending", "book-of-the-day"].includes(t) && !t.startsWith("store:")),
    categories: pick(CATS),
    badges: [
      ...(tags.includes("bestseller") ? ["BESTSELLER"] : []),
      ...(tags.includes("featured") ? ["FEATURED"] : []),
      ...(isNew ? ["NEW"] : []),
    ],
    isNew,
    trending: tags.includes("trending") || tags.includes("bestseller"),
    bookOfDay: tags.includes("book-of-the-day"),
    variantId: (p.variants?.nodes?.[0]?.id ?? "").split("/").pop() || undefined,
    store: (tags.find((t) => t.startsWith("store:")) ?? "store:abc-bookstore").replace("store:", ""),
    blurb: p.description ?? "",
  };
});

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/sync-shopify.mjs — do not hand-edit.\n` +
    `import type { Book } from "./books";\n` +
    `export const SHOPIFY_BOOKS: Book[] = ${JSON.stringify(books, null, 2)};\n` +
    `export const SHOPIFY_DOMAIN = ${JSON.stringify(process.env.SHOPIFY_CHECKOUT_DOMAIN || domain)};\n`
);
console.log(`sync-shopify: wrote ${books.length} products.`);

// ---- Site content managed in Shopify admin → Content → Metaobjects ----
const moQuery = (type) => `{ metaobjects(type: "${type}", first: 100) { nodes { handle fields { key value
  reference { ... on MediaImage { image { url } } ... on Product { handle } } } } } }`;
async function fetchType(type) {
  const r = await fetch(`https://${domain}/api/2026-01/graphql.json`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-Shopify-Storefront-Access-Token": token },
    body: JSON.stringify({ query: moQuery(type) }),
  });
  const j = await r.json();
  return (j.data?.metaobjects?.nodes ?? []).map((n) => {
    const o = { handle: n.handle };
    for (const f of n.fields) o[f.key] = f.reference?.image?.url ?? f.reference?.handle ?? f.value;
    return o;
  });
}
const on = (o) => o.active !== "false";
const byPos = (a, b) => (parseInt(a.position ?? "999", 10) || 999) - (parseInt(b.position ?? "999", 10) || 999);
const today = new Date().toISOString().slice(0, 10);
const [slides, tiles, budgets, gifts, stores, home] = await Promise.all(
  ["ak_promo_slide", "ak_tile", "ak_budget", "ak_gift_box", "ak_bookstore", "ak_homepage"].map(fetchType)
);
const tileOf = (kind, base) => tiles.filter((t) => t.kind === kind && on(t)).sort(byPos)
  .map((t) => ({ slug: t.tag, label: t.label, sub: t.subtitle ?? "", icon: "", href: `/${base}/${t.tag}`, ...(t.image ? { image: t.image } : {}) }));
const content = {
  promos: slides.filter(on).filter((s) => (!s.start_date || s.start_date <= today) && (!s.end_date || s.end_date >= today)).sort(byPos)
    .map((s) => ({ heading: s.heading, lead: s.lead ?? "", book: s.book, note: s.note ?? "", cta: s.button_text || "Shop now", photo: s.photo })),
  categories: tileOf("Category", "category"),
  moods: tileOf("Mood", "mood"),
  exams: tileOf("Exam", "exam"),
  budgets: budgets.filter(on).sort(byPos).map((b) => ({ slug: b.handle, label: b.label, max: parseInt(b.max_price, 10) })),
  giftBoxes: gifts.filter(on).sort(byPos).map((g) => ({ slug: g.handle, name: g.name, items: JSON.parse(g.contents ?? "[]"), price: parseInt(g.price, 10), photo: g.photo, ...(g.product ? { product: g.product } : {}) })),
  stores: stores.filter(on).sort(byPos).map((s) => ({ slug: s.tag, name: s.name, location: s.location, about: s.about ?? "", phone: s.phone ?? "", tag: `store:${s.tag}`, photo: s.photo ?? "" })),
  home: home[0] ?? null,
};
writeFileSync(
  new URL("../src/data/site-content.ts", import.meta.url),
  `// AUTO-GENERATED by scripts/sync-shopify.mjs from Shopify metaobjects — do not hand-edit.\n` +
    `export const SITE_CONTENT: Record<string, any> | null = ${JSON.stringify(content, null, 2)};\n`
);
console.log(`sync-shopify: content — ${content.promos.length} slides, ${content.categories.length + content.moods.length + content.exams.length} tiles, ${content.budgets.length} budgets, ${content.giftBoxes.length} gift boxes, ${content.stores.length} stores.`);
