// Pulls the live catalog from Shopify Storefront API and writes
// src/data/shopify-catalog.ts. No token? Keeps the demo catalog untouched.
// Usage: SHOPIFY_STORE_DOMAIN=x.myshopify.com SHOPIFY_STOREFRONT_TOKEN=shpsa_... node scripts/sync-shopify.mjs
import { writeFileSync, existsSync } from "node:fs";

const domain = process.env.SHOPIFY_STORE_DOMAIN;
const token = process.env.SHOPIFY_STOREFRONT_TOKEN;
const out = new URL("../src/data/shopify-catalog.ts", import.meta.url);

if (!domain || !token) {
  console.log("sync-shopify: no SHOPIFY_STORE_DOMAIN/TOKEN — keeping demo catalog.");
  process.exit(0);
}

const query = `{
  products(first: 100) {
    nodes {
      handle title vendor tags
      description(truncateAt: 220)
      featuredImage { url altText }
      priceRange { minVariantPrice { amount } }
      compareAtPriceRange { minVariantPrice { amount } }
      variants(first: 1) { nodes { sku } }
      metafields(identifiers: [
        {namespace:"custom",key:"publisher"},{namespace:"custom",key:"pages"},
        {namespace:"custom",key:"language"},{namespace:"custom",key:"edition"},
        {namespace:"custom",key:"genre"}
      ]) { key value }
    }
  }
}`;

const res = await fetch(`https://${domain}/api/2026-01/graphql.json`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    "X-Shopify-Storefront-Access-Token": token,
  },
  body: JSON.stringify({ query }),
});
if (!res.ok) {
  console.error(`sync-shopify: HTTP ${res.status} — keeping demo catalog.`);
  process.exit(0);
}
const json = await res.json();
if (json.errors) {
  console.error("sync-shopify:", JSON.stringify(json.errors).slice(0, 300));
  process.exit(0);
}

const MOODS = ["feel", "thrill", "learn", "reflect", "love", "grow", "escape", "light"];
const CATS = ["fiction", "mystery-thriller", "self-help", "hindi-literature", "english-literature", "biography-history", "children", "education-exams", "maths-science"];

const books = (json.data?.products?.nodes ?? []).map((p) => {
  const tags = (p.tags ?? []).map((t) => t.toLowerCase());
  const mf = Object.fromEntries((p.metafields ?? []).filter(Boolean).map((m) => [m.key, m.value]));
  const price = Math.round(parseFloat(p.priceRange?.minVariantPrice?.amount ?? "0"));
  const mrpRaw = parseFloat(p.compareAtPriceRange?.minVariantPrice?.amount ?? "0");
  const pick = (list) => list.filter((x) => tags.includes(x));
  const isNew = tags.includes("newarrival") || tags.includes("new");
  return {
    slug: p.handle,
    title: p.title,
    author: p.vendor || "Aapki Kitab",
    isbn: p.variants?.nodes?.[0]?.sku ?? null,
    publisher: mf.publisher ?? "",
    pages: parseInt(mf.pages ?? "0", 10) || 0,
    language: mf.language ?? "English",
    edition: mf.edition ?? "",
    genre: mf.genre ?? "",
    price,
    mrp: mrpRaw > price ? Math.round(mrpRaw) : price,
    rating: 4.5,
    reviews: 0,
    cover: p.featuredImage?.url ?? null,
    coverTint: "#4b0f8a",
    moods: pick(MOODS),
    exams: tags.filter((t) => !MOODS.includes(t) && !CATS.includes(t) && !["newarrival", "new", "bestseller", "featured", "trending"].includes(t) && !t.startsWith("store:")),
    categories: pick(CATS),
    badges: [
      ...(tags.includes("bestseller") ? ["BESTSELLER"] : []),
      ...(tags.includes("featured") ? ["FEATURED"] : []),
      ...(isNew ? ["NEW"] : []),
    ],
    isNew,
    trending: tags.includes("trending") || tags.includes("bestseller"),
    store: (tags.find((t) => t.startsWith("store:")) ?? "store:abc-bookstore").replace("store:", ""),
    blurb: p.description ?? "",
  };
});

writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/sync-shopify.mjs — do not hand-edit.\n` +
    `import type { Book } from "./books";\n` +
    `export const SHOPIFY_BOOKS: Book[] = ${JSON.stringify(books, null, 2)};\n`
);
console.log(`sync-shopify: wrote ${books.length} products.`);
