// AUTO-GENERATED by scripts/sync-shopify.mjs — do not hand-edit.
// Empty until the first sync with SHOPIFY_STORE_DOMAIN + SHOPIFY_STOREFRONT_TOKEN.
import type { Book } from "./books";

export const SHOPIFY_BOOKS: Book[] = [];
