// AUTO-GENERATED by scripts/sync-shopify.mjs — do not hand-edit.
import type { Book } from "./books";
export const SHOPIFY_BOOKS: Book[] = [
  {
    "slug": "parth-the-promise",
    "title": "Parth: The Promise",
    "author": "Himanshu Sharma",
    "isbn": null,
    "publisher": "Aapki Kitab Press",
    "pages": 312,
    "language": "English",
    "edition": "1st",
    "genre": "Fiction",
    "price": 299,
    "mrp": 399,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "love"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "english-literature"
    ],
    "badges": [
      "FEATURED",
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": true,
    "variantId": "53671523975457",
    "store": "abc-bookstore",
    "blurb": "Discover the magic of Udaipur in this tale of faith, mystery and a promise waiting to be fulfilled. Book 1 of the Duology."
  },
  {
    "slug": "atomic-habits",
    "title": "Atomic Habits",
    "author": "James Clear",
    "isbn": "9780735211292",
    "publisher": "Random House",
    "pages": 320,
    "language": "English",
    "edition": "1st",
    "genre": "Self Help",
    "price": 899,
    "mrp": 1199,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive.jpg?v=1791108048",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524008225",
    "store": "abc-bookstore",
    "blurb": "Tiny changes, remarkable results — the definitive guide to building good habits and breaking bad ones."
  },
  {
    "slug": "the-alchemist",
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "isbn": "9780061122415",
    "publisher": "HarperOne",
    "pages": 208,
    "language": "English",
    "edition": "Reprint",
    "genre": "Fiction",
    "price": 350,
    "mrp": 499,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_68ce3329-671a-47a5-8a5a-0bf9869c1d69.jpg?v=1791108049",
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "love",
      "escape"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "english-literature"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524040993",
    "store": "kitab-ghar",
    "blurb": "Santiago's journey to find treasure becomes a fable about following your dream."
  },
  {
    "slug": "ikigai",
    "title": "Ikigai: The Japanese Secret to a Long and Happy Life",
    "author": "Héctor García & Francesc Miralles",
    "isbn": "9781786330895",
    "publisher": "Hutchinson",
    "pages": 208,
    "language": "English",
    "edition": "1st",
    "genre": "Self Help",
    "price": 550,
    "mrp": 750,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_32ebc91e-f32c-454a-8d85-a15db7a3b897.jpg?v=1791108049",
    "coverTint": "#4b0f8a",
    "moods": [
      "reflect",
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524073761",
    "store": "abc-bookstore",
    "blurb": "The Japanese philosophy of purpose and joy, from the centenarians of Okinawa."
  },
  {
    "slug": "psychology-of-money",
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "isbn": "9780857197689",
    "publisher": "Harriman House",
    "pages": 256,
    "language": "English",
    "edition": "1st",
    "genre": "Finance",
    "price": 499,
    "mrp": 699,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/9780857197689-L.jpg?v=1791108050",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help",
      "biography-history"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524106529",
    "store": "kitab-ghar",
    "blurb": "Timeless lessons on wealth, greed, and happiness — doing well with money has surprisingly little to do with how smart you are."
  },
  {
    "slug": "rich-dad-poor-dad",
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki",
    "isbn": "9781612680194",
    "publisher": "Plata",
    "pages": 336,
    "language": "English",
    "edition": "20th Anniversary",
    "genre": "Finance",
    "price": 399,
    "mrp": 599,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_843df97e-dbea-4fb4-8b87-10a7e5869913.jpg?v=1791108052",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524139297",
    "store": "abc-bookstore",
    "blurb": "What the rich teach their kids about money that the poor and middle class do not."
  },
  {
    "slug": "the-silent-patient",
    "title": "The Silent Patient",
    "author": "Alex Michaelides",
    "isbn": "9781250301697",
    "publisher": "Celadon Books",
    "pages": 336,
    "language": "English",
    "edition": "1st",
    "genre": "Thriller",
    "price": 449,
    "mrp": 650,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_ecc7ad8b-b208-4701-9eac-48fefe54df17.jpg?v=1791108053",
    "coverTint": "#4b0f8a",
    "moods": [
      "thrill"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "mystery-thriller"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524172065",
    "store": "kitab-ghar",
    "blurb": "Alicia Berenson shot her husband five times and never spoke another word. A psychotherapist is determined to unravel her mystery."
  },
  {
    "slug": "sapiens",
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "isbn": "9780062316097",
    "publisher": "Harper",
    "pages": 464,
    "language": "English",
    "edition": "1st",
    "genre": "History",
    "price": 499,
    "mrp": 799,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_484fb0ef-6d16-424f-a106-f88ca7dbe649.jpg?v=1791108053",
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "upsc"
    ],
    "categories": [
      "biography-history"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524204833",
    "store": "abc-bookstore",
    "blurb": "How did our species conquer the world? A provocative history of humankind."
  },
  {
    "slug": "wings-of-fire",
    "title": "Wings of Fire: An Autobiography",
    "author": "A. P. J. Abdul Kalam",
    "isbn": "9788173711466",
    "publisher": "Universities Press",
    "pages": 180,
    "language": "English",
    "edition": "Reprint",
    "genre": "Biography",
    "price": 350,
    "mrp": 450,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/9788173711466-L.jpg?v=1791108053",
    "coverTint": "#4b0f8a",
    "moods": [
      "learn",
      "grow"
    ],
    "exams": [
      "ssc",
      "upsc"
    ],
    "categories": [
      "biography-history"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524237601",
    "store": "kitab-ghar",
    "blurb": "The inspiring life story of Dr. Kalam, from Rameswaram to Rashtrapati Bhavan."
  },
  {
    "slug": "train-to-pakistan",
    "title": "Train to Pakistan",
    "author": "Khushwant Singh",
    "isbn": "9780802132215",
    "publisher": "Grove Press",
    "pages": 192,
    "language": "English",
    "edition": "Reprint",
    "genre": "Historical Fiction",
    "price": 179,
    "mrp": 250,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_d7759d6a-1bb9-443d-a591-1822213c9047.jpg?v=1791108055",
    "coverTint": "#4b0f8a",
    "moods": [
      "reflect"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "english-literature",
      "biography-history"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524270369",
    "store": "abc-bookstore",
    "blurb": "A searing Partition novel set in the village of Mano Majra — Singh's finest."
  },
  {
    "slug": "godan",
    "title": "Godan (गोदान)",
    "author": "Munshi Premchand",
    "isbn": "8176501662",
    "publisher": "Jaico",
    "pages": 344,
    "language": "Hindi",
    "edition": "Reprint",
    "genre": "Classic",
    "price": 149,
    "mrp": 225,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_4adcbcd1-ca9d-479f-bc34-0ec6da40c1fd.jpg?v=1791108056",
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "reflect"
    ],
    "exams": [
      "school",
      "upsc"
    ],
    "categories": [
      "fiction",
      "hindi-literature"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524303137",
    "store": "kitab-ghar",
    "blurb": "Premchand's immortal classic of peasant India — the novel every Hindi reader returns to."
  },
  {
    "slug": "harry-potter-1",
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J. K. Rowling",
    "isbn": "9780747532699",
    "publisher": "Bloomsbury",
    "pages": 336,
    "language": "English",
    "edition": "Reprint",
    "genre": "Fantasy",
    "price": 650,
    "mrp": 899,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_7541fb5a-755c-4fc2-97eb-8804a9be3557.jpg?v=1791108057",
    "coverTint": "#4b0f8a",
    "moods": [
      "escape"
    ],
    "exams": [
      "school"
    ],
    "categories": [
      "fiction",
      "children"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "53671524335905",
    "store": "abc-bookstore",
    "blurb": "Harry discovers he is a wizard and begins his first year at Hogwarts."
  },
  {
    "slug": "matilda",
    "title": "Matilda",
    "author": "Roald Dahl",
    "isbn": "9780142410370",
    "publisher": "Puffin",
    "pages": 240,
    "language": "English",
    "edition": "Reprint",
    "genre": "Children",
    "price": 350,
    "mrp": 450,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_a0d5de2b-e3a9-4746-b9ae-ed4b88804e58.jpg?v=1791108057",
    "coverTint": "#4b0f8a",
    "moods": [
      "light"
    ],
    "exams": [
      "school"
    ],
    "categories": [
      "children"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524368673",
    "store": "kitab-ghar",
    "blurb": "Matilda's parents think she's a nuisance, but she is a genius — with extraordinary powers."
  },
  {
    "slug": "quantitative-aptitude",
    "title": "Quantitative Aptitude for Competitive Examinations",
    "author": "R. S. Aggarwal",
    "isbn": "9788121924986",
    "publisher": "S. Chand",
    "pages": 960,
    "language": "English",
    "edition": "Revised",
    "genre": "Exam Prep",
    "price": 725,
    "mrp": 945,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "banking",
      "railway",
      "ssc"
    ],
    "categories": [
      "education-exams",
      "maths-science"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524401441",
    "store": "abc-bookstore",
    "blurb": "The bible of aptitude preparation — SSC, Banking, Railway and all competitive exams."
  },
  {
    "slug": "pride-and-prejudice",
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "isbn": "9780141439518",
    "publisher": "Maple Press",
    "pages": 432,
    "language": "English",
    "edition": "Reprint",
    "genre": "Romance Classic",
    "price": 250,
    "mrp": 350,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_a5387b2d-6f21-4499-9124-a075360730ce.jpg?v=1791108059",
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "love"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "english-literature"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524434209",
    "store": "kitab-ghar",
    "blurb": "Elizabeth Bennet spars with Mr. Darcy in Austen's sparkling comedy of manners."
  },
  {
    "slug": "word-power-made-easy",
    "title": "Word Power Made Easy",
    "author": "Norman Lewis",
    "isbn": "0808504053",
    "publisher": "Goyal Publishers",
    "pages": 656,
    "language": "English",
    "edition": "Revised",
    "genre": "Exam Prep",
    "price": 199,
    "mrp": 275,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/view_archive_dbfb4921-db45-473f-9856-1aea2dd9ce90.jpg?v=1791108060",
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "banking",
      "cat",
      "ssc"
    ],
    "categories": [
      "education-exams"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524466977",
    "store": "abc-bookstore",
    "blurb": "The legendary vocabulary builder — essential for Banking, SSC, CAT and all competitive exams."
  },
  {
    "slug": "indian-polity",
    "title": "Indian Polity for Civil Services Examinations",
    "author": "M. Laxmikanth",
    "isbn": "9789382249276",
    "publisher": "McGraw Hill",
    "pages": 864,
    "language": "English",
    "edition": "7th",
    "genre": "Exam Prep",
    "price": 750,
    "mrp": 950,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "upsc"
    ],
    "categories": [
      "education-exams"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "53671524499745",
    "store": "kitab-ghar",
    "blurb": "The definitive UPSC polity reference — constitution, governance and current updates."
  }
];
export const SHOPIFY_DOMAIN = "aapkikitab.myshopify.com";
