// AUTO-GENERATED by scripts/sync-shopify.mjs — do not hand-edit.
import type { Book } from "./books";
export const SHOPIFY_BOOKS: Book[] = [
  {
    "kind": "book",
    "slug": "parth-the-promise",
    "title": "Parth: The Promise",
    "author": "Himanshu Sharma",
    "isbn": null,
    "publisher": "Aapki Kitab Press",
    "pages": 312,
    "language": "English",
    "edition": "1st",
    "genre": "Fiction",
    "price": 299,
    "mrp": 399,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "love"
    ],
    "exams": [],
    "categories": [
      "english-literature",
      "fiction"
    ],
    "badges": [
      "FEATURED",
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": true,
    "variantId": "67614414766212",
    "store": "abc-bookstore",
    "blurb": "Discover the magic of Udaipur in this tale of faith, mystery and a promise waiting to be fulfilled. Book 1 of the Duology."
  },
  {
    "kind": "book",
    "slug": "atomic-habits",
    "title": "Atomic Habits",
    "author": "James Clear",
    "isbn": "9780735211292",
    "publisher": "Random House",
    "pages": 320,
    "language": "English",
    "edition": "1st",
    "genre": "Self Help",
    "price": 899,
    "mrp": 1199,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive.jpg?v=1791273184",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614414831748",
    "store": "abc-bookstore",
    "blurb": "Tiny changes, remarkable results — the definitive guide to building good habits and breaking bad ones."
  },
  {
    "kind": "book",
    "slug": "the-alchemist",
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "isbn": "9780061122415",
    "publisher": "HarperOne",
    "pages": 208,
    "language": "English",
    "edition": "Reprint",
    "genre": "Fiction",
    "price": 350,
    "mrp": 499,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_68ce3329-671a-47a5-8a5a-0bf9869c1d69.jpg?v=1791273185",
    "coverTint": "#4b0f8a",
    "moods": [
      "escape",
      "feel",
      "love"
    ],
    "exams": [],
    "categories": [
      "english-literature",
      "fiction"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614414897284",
    "store": "kitab-ghar",
    "blurb": "Santiago's journey to find treasure becomes a fable about following your dream."
  },
  {
    "kind": "book",
    "slug": "ikigai",
    "title": "Ikigai: The Japanese Secret to a Long and Happy Life",
    "author": "Héctor García & Francesc Miralles",
    "isbn": "9781786330895",
    "publisher": "Hutchinson",
    "pages": 208,
    "language": "English",
    "edition": "1st",
    "genre": "Self Help",
    "price": 550,
    "mrp": 750,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_32ebc91e-f32c-454a-8d85-a15db7a3b897.jpg?v=1791273187",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow",
      "reflect"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614414962820",
    "store": "abc-bookstore",
    "blurb": "The Japanese philosophy of purpose and joy, from the centenarians of Okinawa."
  },
  {
    "kind": "book",
    "slug": "psychology-of-money",
    "title": "The Psychology of Money",
    "author": "Morgan Housel",
    "isbn": "9780857197689",
    "publisher": "Harriman House",
    "pages": 256,
    "language": "English",
    "edition": "1st",
    "genre": "Finance",
    "price": 499,
    "mrp": 699,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/9780857197689-L.jpg?v=1791273188",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "biography-history",
      "self-help"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614415061124",
    "store": "kitab-ghar",
    "blurb": "Timeless lessons on wealth, greed, and happiness — doing well with money has surprisingly little to do with how smart you are."
  },
  {
    "kind": "book",
    "slug": "rich-dad-poor-dad",
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki",
    "isbn": "9781612680194",
    "publisher": "Plata",
    "pages": 336,
    "language": "English",
    "edition": "20th Anniversary",
    "genre": "Finance",
    "price": 399,
    "mrp": 599,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_843df97e-dbea-4fb4-8b87-10a7e5869913.jpg?v=1791273190",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow"
    ],
    "exams": [],
    "categories": [
      "self-help"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614415126660",
    "store": "abc-bookstore",
    "blurb": "What the rich teach their kids about money that the poor and middle class do not."
  },
  {
    "kind": "book",
    "slug": "the-silent-patient",
    "title": "The Silent Patient",
    "author": "Alex Michaelides",
    "isbn": "9781250301697",
    "publisher": "Celadon Books",
    "pages": 336,
    "language": "English",
    "edition": "1st",
    "genre": "Thriller",
    "price": 449,
    "mrp": 650,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_ecc7ad8b-b208-4701-9eac-48fefe54df17.jpg?v=1791273193",
    "coverTint": "#4b0f8a",
    "moods": [
      "thrill"
    ],
    "exams": [],
    "categories": [
      "fiction",
      "mystery-thriller"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614415159428",
    "store": "kitab-ghar",
    "blurb": "Alicia Berenson shot her husband five times and never spoke another word. A psychotherapist is determined to unravel her mystery."
  },
  {
    "kind": "book",
    "slug": "sapiens",
    "title": "Sapiens: A Brief History of Humankind",
    "author": "Yuval Noah Harari",
    "isbn": "9780062316097",
    "publisher": "Harper",
    "pages": 464,
    "language": "English",
    "edition": "1st",
    "genre": "History",
    "price": 499,
    "mrp": 799,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_484fb0ef-6d16-424f-a106-f88ca7dbe649.jpg?v=1791273193",
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "upsc"
    ],
    "categories": [
      "biography-history"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415192196",
    "store": "abc-bookstore",
    "blurb": "How did our species conquer the world? A provocative history of humankind."
  },
  {
    "kind": "book",
    "slug": "wings-of-fire",
    "title": "Wings of Fire: An Autobiography",
    "author": "A. P. J. Abdul Kalam",
    "isbn": "9788173711466",
    "publisher": "Universities Press",
    "pages": 180,
    "language": "English",
    "edition": "Reprint",
    "genre": "Biography",
    "price": 350,
    "mrp": 450,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/9788173711466-L.jpg?v=1791273195",
    "coverTint": "#4b0f8a",
    "moods": [
      "grow",
      "learn"
    ],
    "exams": [
      "ssc",
      "upsc"
    ],
    "categories": [
      "biography-history"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415224964",
    "store": "kitab-ghar",
    "blurb": "The inspiring life story of Dr. Kalam, from Rameswaram to Rashtrapati Bhavan."
  },
  {
    "kind": "book",
    "slug": "train-to-pakistan",
    "title": "Train to Pakistan",
    "author": "Khushwant Singh",
    "isbn": "9780802132215",
    "publisher": "Grove Press",
    "pages": 192,
    "language": "English",
    "edition": "Reprint",
    "genre": "Historical Fiction",
    "price": 179,
    "mrp": 250,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_d7759d6a-1bb9-443d-a591-1822213c9047.jpg?v=1791273197",
    "coverTint": "#4b0f8a",
    "moods": [
      "reflect"
    ],
    "exams": [],
    "categories": [
      "biography-history",
      "english-literature",
      "fiction"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415257732",
    "store": "abc-bookstore",
    "blurb": "A searing Partition novel set in the village of Mano Majra — Singh's finest."
  },
  {
    "kind": "book",
    "slug": "godan",
    "title": "Godan (गोदान)",
    "author": "Munshi Premchand",
    "isbn": "8176501662",
    "publisher": "Jaico",
    "pages": 344,
    "language": "Hindi",
    "edition": "Reprint",
    "genre": "Classic",
    "price": 149,
    "mrp": 225,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_4adcbcd1-ca9d-479f-bc34-0ec6da40c1fd.jpg?v=1791273199",
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "reflect"
    ],
    "exams": [
      "school",
      "upsc"
    ],
    "categories": [
      "fiction",
      "hindi-literature"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415290500",
    "store": "kitab-ghar",
    "blurb": "Premchand's immortal classic of peasant India — the novel every Hindi reader returns to."
  },
  {
    "kind": "book",
    "slug": "harry-potter-1",
    "title": "Harry Potter and the Philosopher's Stone",
    "author": "J. K. Rowling",
    "isbn": "9780747532699",
    "publisher": "Bloomsbury",
    "pages": 336,
    "language": "English",
    "edition": "Reprint",
    "genre": "Fantasy",
    "price": 650,
    "mrp": 899,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_7541fb5a-755c-4fc2-97eb-8804a9be3557.jpg?v=1791273201",
    "coverTint": "#4b0f8a",
    "moods": [
      "escape"
    ],
    "exams": [
      "school"
    ],
    "categories": [
      "children",
      "fiction"
    ],
    "badges": [
      "BESTSELLER"
    ],
    "isNew": false,
    "trending": true,
    "bookOfDay": false,
    "variantId": "67614415323268",
    "store": "abc-bookstore",
    "blurb": "Harry discovers he is a wizard and begins his first year at Hogwarts."
  },
  {
    "kind": "book",
    "slug": "matilda",
    "title": "Matilda",
    "author": "Roald Dahl",
    "isbn": "9780142410370",
    "publisher": "Puffin",
    "pages": 240,
    "language": "English",
    "edition": "Reprint",
    "genre": "Children",
    "price": 350,
    "mrp": 450,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_a0d5de2b-e3a9-4746-b9ae-ed4b88804e58.jpg?v=1791273202",
    "coverTint": "#4b0f8a",
    "moods": [
      "light"
    ],
    "exams": [
      "school"
    ],
    "categories": [
      "children"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415356036",
    "store": "kitab-ghar",
    "blurb": "Matilda's parents think she's a nuisance, but she is a genius — with extraordinary powers."
  },
  {
    "kind": "book",
    "slug": "quantitative-aptitude",
    "title": "Quantitative Aptitude for Competitive Examinations",
    "author": "R. S. Aggarwal",
    "isbn": "9788121924986",
    "publisher": "S. Chand",
    "pages": 960,
    "language": "English",
    "edition": "Revised",
    "genre": "Exam Prep",
    "price": 725,
    "mrp": 945,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "banking",
      "maths-science",
      "railway",
      "ssc"
    ],
    "categories": [
      "education-exams",
      "maths-science"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415388804",
    "store": "abc-bookstore",
    "blurb": "The bible of aptitude preparation — SSC, Banking, Railway and all competitive exams."
  },
  {
    "kind": "book",
    "slug": "pride-and-prejudice",
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "isbn": "9780141439518",
    "publisher": "Maple Press",
    "pages": 432,
    "language": "English",
    "edition": "Reprint",
    "genre": "Romance Classic",
    "price": 250,
    "mrp": 350,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_a5387b2d-6f21-4499-9124-a075360730ce.jpg?v=1791273205",
    "coverTint": "#4b0f8a",
    "moods": [
      "feel",
      "love"
    ],
    "exams": [],
    "categories": [
      "english-literature",
      "fiction"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415454340",
    "store": "kitab-ghar",
    "blurb": "Elizabeth Bennet spars with Mr. Darcy in Austen's sparkling comedy of manners."
  },
  {
    "kind": "book",
    "slug": "word-power-made-easy",
    "title": "Word Power Made Easy",
    "author": "Norman Lewis",
    "isbn": "0808504053",
    "publisher": "Goyal Publishers",
    "pages": 656,
    "language": "English",
    "edition": "Revised",
    "genre": "Exam Prep",
    "price": 199,
    "mrp": 275,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/view_archive_dbfb4921-db45-473f-9856-1aea2dd9ce90.jpg?v=1791273207",
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "banking",
      "cat",
      "ssc"
    ],
    "categories": [
      "education-exams"
    ],
    "badges": [
      "NEW"
    ],
    "isNew": true,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415519876",
    "store": "abc-bookstore",
    "blurb": "The legendary vocabulary builder — essential for Banking, SSC, CAT and all competitive exams."
  },
  {
    "kind": "book",
    "slug": "indian-polity",
    "title": "Indian Polity for Civil Services Examinations",
    "author": "M. Laxmikanth",
    "isbn": "9789382249276",
    "publisher": "McGraw Hill",
    "pages": 864,
    "language": "English",
    "edition": "7th",
    "genre": "Exam Prep",
    "price": 750,
    "mrp": 950,
    "rating": 0,
    "reviews": 0,
    "cover": null,
    "coverTint": "#4b0f8a",
    "moods": [
      "learn"
    ],
    "exams": [
      "upsc"
    ],
    "categories": [
      "education-exams"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415552644",
    "store": "kitab-ghar",
    "blurb": "The definitive UPSC polity reference — constitution, governance and current updates."
  },
  {
    "kind": "craft",
    "slug": "paint-brush-set",
    "title": "Artist Paint Brush Set (12 pcs)",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 349,
    "mrp": 450,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1460661419201-fd4cecdf8a8b.jpg?v=1791273211",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "art-supplies"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415585412",
    "store": "abc-bookstore",
    "blurb": "Twelve brushes in round, flat and filbert shapes for acrylic, watercolour and gouache."
  },
  {
    "kind": "craft",
    "slug": "acrylic-colour-set",
    "title": "Acrylic Colour Set (12 shades)",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 549,
    "mrp": 699,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1513364776144-60967b0f800f.jpg?v=1791273211",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "art-supplies"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415618180",
    "store": "abc-bookstore",
    "blurb": "Rich, fast-drying acrylics in twelve mixable shades, with a starter brush."
  },
  {
    "kind": "craft",
    "slug": "art-supplies-case",
    "title": "Complete Art Supplies Case",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 1299,
    "mrp": 1599,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1456735190827-d1262f71b8a3.jpg?v=1791273214",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "art-supplies"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415650948",
    "store": "abc-bookstore",
    "blurb": "Pencils, markers, crayons and colours in one portable case for school and hobby artists."
  },
  {
    "kind": "craft",
    "slug": "journal-and-pen-set",
    "title": "Ruled Journal & Fountain Pen Set",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 449,
    "mrp": 599,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1517842645767-c639042777db.jpg?v=1791273215",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "notebooks"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415683716",
    "store": "abc-bookstore",
    "blurb": "A hardbound ruled journal paired with a smooth fountain pen. A thoughtful gift for writers."
  },
  {
    "kind": "craft",
    "slug": "spiral-sketchbooks",
    "title": "Spiral Sketchbooks, A4 (pack of 3)",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 299,
    "mrp": 399,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1531346878377-a5be20888e57.jpg?v=1791273216",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "notebooks"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415716484",
    "store": "abc-bookstore",
    "blurb": "Thick 140 gsm pages that take pencil, ink and light washes."
  },
  {
    "kind": "craft",
    "slug": "craft-starter-kit",
    "title": "Craft Starter Kit",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 399,
    "mrp": 499,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1452860606245-08befc0ff44b.jpg?v=1791273218",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "craft-kits"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415749252",
    "store": "abc-bookstore",
    "blurb": "Washi tape, scissors, a craft knife, sticky notes and a ruler for school projects and journaling."
  },
  {
    "kind": "craft",
    "slug": "classic-fountain-pen",
    "title": "Classic Fountain Pen",
    "author": "Aapki Kitab",
    "isbn": null,
    "publisher": "",
    "pages": 0,
    "language": "English",
    "edition": "",
    "genre": "",
    "price": 249,
    "mrp": 349,
    "rating": 0,
    "reviews": 0,
    "cover": "https://cdn.shopify.com/s/files/1/1033/0659/2388/files/photo-1585336261022-680e295ce3fe.jpg?v=1791273219",
    "coverTint": "#4b0f8a",
    "moods": [],
    "exams": [],
    "categories": [
      "pens"
    ],
    "badges": [],
    "isNew": false,
    "trending": false,
    "bookOfDay": false,
    "variantId": "67614415782020",
    "store": "abc-bookstore",
    "blurb": "A balanced steel-nib fountain pen with a converter. Writes smooth from the first line."
  }
];
export const SHOPIFY_DOMAIN = "aapki-kitab-iysbgwrj.myshopify.com";
