// AUTO-GENERATED by scripts/sync-shopify.mjs from Shopify metaobjects — do not hand-edit.
export const SITE_CONTENT: Record<string, any> | null = {
  "promos": [
    {
      "heading": "Stories that stay with you",
      "lead": "Discover the magic of Udaipur in",
      "book": "parth-the-promise",
      "note": "A novel · Book 1 of the Duology",
      "cta": "Buy now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1474932430478-367dbb6832c1.jpg?v=1791112582"
    },
    {
      "heading": "Exam season, sorted",
      "lead": "The prep book every aspirant keeps close",
      "book": "quantitative-aptitude",
      "note": "SSC · Banking · Railway",
      "cta": "Shop now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1497633762265-9d179a990aa6.jpg?v=1791112582"
    },
    {
      "heading": "Hindi sahitya, timeless",
      "lead": "Premchand's masterpiece, for every shelf",
      "book": "godan",
      "note": "Classic Hindi literature",
      "cta": "Shop now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1526243741027-444d633d7365.jpg?v=1791112582"
    }
  ],
  "categories": [
    {
      "slug": "fiction",
      "label": "Fiction",
      "sub": "Stories",
      "icon": "",
      "href": "/category/fiction"
    },
    {
      "slug": "mystery-thriller",
      "label": "Mystery & Thriller",
      "sub": "Page-turners",
      "icon": "",
      "href": "/category/mystery-thriller"
    },
    {
      "slug": "self-help",
      "label": "Self Help",
      "sub": "Become more",
      "icon": "",
      "href": "/category/self-help"
    },
    {
      "slug": "hindi-literature",
      "label": "Hindi Literature",
      "sub": "साहित्य",
      "icon": "",
      "href": "/category/hindi-literature"
    },
    {
      "slug": "english-literature",
      "label": "English Literature",
      "sub": "Classics",
      "icon": "",
      "href": "/category/english-literature"
    },
    {
      "slug": "biography-history",
      "label": "Biography & History",
      "sub": "Real lives",
      "icon": "",
      "href": "/category/biography-history"
    },
    {
      "slug": "children",
      "label": "Children",
      "sub": "Young readers",
      "icon": "",
      "href": "/category/children"
    },
    {
      "slug": "education-exams",
      "label": "Education & Exams",
      "sub": "Prep",
      "icon": "",
      "href": "/category/education-exams"
    },
    {
      "slug": "maths-science",
      "label": "Maths & Science",
      "sub": "Concepts",
      "icon": "",
      "href": "/category/maths-science"
    }
  ],
  "moods": [
    {
      "slug": "feel",
      "label": "Feel",
      "sub": "Emotional",
      "icon": "",
      "href": "/mood/feel"
    },
    {
      "slug": "thrill",
      "label": "Thrill",
      "sub": "Mystery & Thriller",
      "icon": "",
      "href": "/mood/thrill"
    },
    {
      "slug": "learn",
      "label": "Learn",
      "sub": "Knowledge",
      "icon": "",
      "href": "/mood/learn"
    },
    {
      "slug": "reflect",
      "label": "Reflect",
      "sub": "Spiritual",
      "icon": "",
      "href": "/mood/reflect"
    },
    {
      "slug": "love",
      "label": "Love",
      "sub": "Romance",
      "icon": "",
      "href": "/mood/love"
    },
    {
      "slug": "grow",
      "label": "Grow",
      "sub": "Self-help",
      "icon": "",
      "href": "/mood/grow"
    },
    {
      "slug": "escape",
      "label": "Escape",
      "sub": "Fiction",
      "icon": "",
      "href": "/mood/escape"
    },
    {
      "slug": "light",
      "label": "Light",
      "sub": "Easy Reads",
      "icon": "",
      "href": "/mood/light"
    }
  ],
  "exams": [
    {
      "slug": "jee",
      "label": "JEE",
      "sub": "Engineering",
      "icon": "",
      "href": "/exam/jee"
    },
    {
      "slug": "neet",
      "label": "NEET",
      "sub": "Medical",
      "icon": "",
      "href": "/exam/neet"
    },
    {
      "slug": "upsc",
      "label": "UPSC",
      "sub": "Civil Services",
      "icon": "",
      "href": "/exam/upsc"
    },
    {
      "slug": "ssc",
      "label": "SSC",
      "sub": "Staff Selection",
      "icon": "",
      "href": "/exam/ssc"
    },
    {
      "slug": "banking",
      "label": "Banking",
      "sub": "IBPS • SBI",
      "icon": "",
      "href": "/exam/banking"
    },
    {
      "slug": "railway",
      "label": "Railway",
      "sub": "RRB • NTPC",
      "icon": "",
      "href": "/exam/railway"
    },
    {
      "slug": "cuet",
      "label": "CUET",
      "sub": "University",
      "icon": "",
      "href": "/exam/cuet"
    },
    {
      "slug": "cat",
      "label": "CAT",
      "sub": "MBA",
      "icon": "",
      "href": "/exam/cat"
    },
    {
      "slug": "gate",
      "label": "GATE",
      "sub": "M.Tech",
      "icon": "",
      "href": "/exam/gate"
    },
    {
      "slug": "school",
      "label": "School",
      "sub": "Class 1–12",
      "icon": "",
      "href": "/exam/school"
    },
    {
      "slug": "college",
      "label": "College",
      "sub": "UG • PG",
      "icon": "",
      "href": "/exam/college"
    },
    {
      "slug": "maths-science",
      "label": "Maths & Science",
      "sub": "Concepts",
      "icon": "",
      "href": "/exam/maths-science"
    }
  ],
  "budgets": [
    {
      "slug": "under-199",
      "label": "Under ₹199",
      "max": 199
    },
    {
      "slug": "under-299",
      "label": "Under ₹299",
      "max": 299
    },
    {
      "slug": "under-499",
      "label": "Under ₹499",
      "max": 499
    },
    {
      "slug": "under-999",
      "label": "Under ₹999",
      "max": 999
    }
  ],
  "giftBoxes": [
    {
      "slug": "book-lover-box",
      "name": "Book Lover Box",
      "items": [
        "1 book of your choice",
        "1 bookmark",
        "1 greeting card"
      ],
      "price": 599,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1512909006721-3d6018887383.jpg?v=1791112582"
    },
    {
      "slug": "birthday-book-box",
      "name": "Birthday Book Box",
      "items": [
        "1 book",
        "1 art / craft item",
        "1 greeting card"
      ],
      "price": 699,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1513885535751-8b9238bd345a.jpg?v=1791112582"
    },
    {
      "slug": "best-friend-box",
      "name": "Best Friend Box",
      "items": [
        "1 book",
        "1 bookmark",
        "1 small gift item"
      ],
      "price": 699,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1544947950-fa07a98d237f.jpg?v=1791112582"
    }
  ],
  "stores": [
    {
      "slug": "abc-bookstore",
      "name": "ABC Bookstore",
      "location": "Johari Bazaar, Jaipur",
      "about": "A family-run bookstore serving Jaipur's readers since 1998. Strong in exam prep, Hindi literature and children's books.",
      "phone": "+91-98290-00000",
      "tag": "store:abc-bookstore",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1481627834876-b7833e8f5570.jpg?v=1791112582"
    },
    {
      "slug": "kitab-ghar",
      "name": "Kitab Ghar",
      "location": "Nai Sarak, Delhi",
      "about": "Old Delhi's beloved book lane veteran. Curated fiction, biographies and classics at honest prices.",
      "phone": "+91-98110-00000",
      "tag": "store:kitab-ghar",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1521587760476-6c12a4b040da.jpg?v=1791112582"
    }
  ],
  "home": {
    "handle": "homepage",
    "announcement_1": null,
    "announcement_2": null,
    "announcement_3": null,
    "show_book_of_day": "true",
    "show_budget": "true",
    "show_categories": "true",
    "show_exams": "true",
    "show_find_book": "true",
    "show_gift_boxes": "true",
    "show_moods": "true",
    "show_new_arrivals": "true",
    "show_reviews": "true",
    "show_slider": "true",
    "show_trending": "true",
    "header_tagline": "Made for India. Made for You.",
    "search_placeholder": "Search for books, gifts, art & craft...",
    "default_delivery_place": "Udaipur, 313001",
    "hero_eyebrow": null,
    "hero_title": "Books|Gifts|Art & Craft|and More",
    "hero_lines": "Made for India.\nMade for You.",
    "hero_button_text": "Shop Now",
    "hero_button_link": "/browse",
    "best_sellers_title": "Best Selling Books",
    "new_arrivals_title": "New Arrivals",
    "show_shortcuts": "true",
    "show_trust_strip": "true",
    "show_promo_tiles": "true"
  },
  "shop": {
    "free_shipping_above": 0,
    "shipping_fee": 0,
    "dispatch_text": "Dispatched in 24–48 hours, delivered in 3–7 working days",
    "return_days": 7,
    "footer_about": "An independent online bookshop. Original books from real Indian bookshops, at honest prices.",
    "newsletter_heading": "New arrivals, every Sunday",
    "payment_methods": [
      "UPI",
      "QR Code",
      "Online Payment"
    ],
    "copyright_text": "© 2026 Aapki Kitab. Made in India.",
    "seo_title": "AapkiKitab — Books, Gifts, Art & Craft",
    "seo_description": "Books, gifts, art & craft and stationery from real Indian bookshops. Discover books by mood, interest, exam and budget.",
    "delivery_headline": "FREE DELIVERY ON EVERY ORDER",
    "delivery_subline": "Across India • No Minimum Order",
    "online_payment_label": "UPI / QR / Online Payment",
    "cod_available": "false",
    "chat_status": "Usually replies within a few hours"
  },
  "shortcuts": [
    {
      "label": "Books",
      "icon": "Books",
      "href": "/browse"
    },
    {
      "label": "Gifts",
      "icon": "Gifts",
      "href": "/#gift-boxes"
    },
    {
      "label": "Art & Craft",
      "icon": "Art & Craft",
      "href": "/art-craft"
    },
    {
      "label": "Stationery",
      "icon": "Stationery",
      "href": "/art-craft?type=notebooks"
    },
    {
      "label": "Exams",
      "icon": "Exams",
      "href": "/category/education-exams"
    },
    {
      "label": "More",
      "icon": "Star",
      "href": "/browse"
    }
  ],
  "trust": [
    {
      "title": "Free Delivery",
      "sub": "Every Order",
      "icon": "Truck",
      "href": ""
    },
    {
      "title": "Secure Payments",
      "sub": "100% Safe",
      "icon": "Shield",
      "href": ""
    },
    {
      "title": "Easy Returns",
      "sub": "7 Days",
      "icon": "Box",
      "href": "/policies"
    },
    {
      "title": "Customer Support",
      "sub": "Always Here",
      "icon": "Headset",
      "href": "/request-book"
    }
  ],
  "promoTiles": [
    {
      "title": "Best Selling Books",
      "sub": "",
      "cta": "Explore Now",
      "href": "/trending",
      "photo": "",
      "colour": "Peach"
    },
    {
      "title": "Unique Gifts",
      "sub": "For Every Occasion",
      "cta": "Shop Now",
      "href": "/#gift-boxes",
      "photo": "",
      "colour": "Lavender"
    }
  ],
  "links": [
    {
      "label": "New Arrivals",
      "href": "/new",
      "placement": "Header menu"
    },
    {
      "label": "Bestsellers",
      "href": "/trending",
      "placement": "Header menu"
    },
    {
      "label": "Art & Craft",
      "href": "/art-craft",
      "placement": "Header menu"
    },
    {
      "label": "Offers",
      "href": "/offers",
      "placement": "Header menu"
    },
    {
      "label": "Bookstores",
      "href": "/bookstores",
      "placement": "Header menu"
    },
    {
      "label": "All books",
      "href": "/browse",
      "placement": "Footer – Shop"
    },
    {
      "label": "New arrivals",
      "href": "/new",
      "placement": "Footer – Shop"
    },
    {
      "label": "Bestsellers",
      "href": "/trending",
      "placement": "Footer – Shop"
    },
    {
      "label": "Art & craft",
      "href": "/art-craft",
      "placement": "Footer – Shop"
    },
    {
      "label": "Offers",
      "href": "/offers",
      "placement": "Footer – Shop"
    },
    {
      "label": "Find my book",
      "href": "/find-my-book",
      "placement": "Footer – Discover"
    },
    {
      "label": "Exams & education",
      "href": "/category/education-exams",
      "placement": "Footer – Discover"
    },
    {
      "label": "Partner bookshops",
      "href": "/bookstores",
      "placement": "Footer – Discover"
    },
    {
      "label": "Request a book",
      "href": "/request-book",
      "placement": "Footer – Discover"
    },
    {
      "label": "Contact us",
      "href": "/request-book",
      "placement": "Footer – Help"
    },
    {
      "label": "Shipping",
      "href": "/policies#shipping",
      "placement": "Footer – Help"
    },
    {
      "label": "Returns & refunds",
      "href": "/policies#returns",
      "placement": "Footer – Help"
    },
    {
      "label": "Privacy & terms",
      "href": "/policies#privacy",
      "placement": "Footer – Help"
    },
    {
      "label": "Customer Reviews",
      "href": "/community",
      "placement": "Header menu"
    },
    {
      "label": "Customer reviews",
      "href": "/community",
      "placement": "Footer – Discover"
    }
  ],
  "craftTypes": [
    {
      "slug": "art-supplies",
      "label": "Art supplies"
    },
    {
      "slug": "notebooks",
      "label": "Notebooks & journals"
    },
    {
      "slug": "craft-kits",
      "label": "Craft kits"
    },
    {
      "slug": "pens",
      "label": "Pens"
    }
  ],
  "policies": []
};
