// AUTO-GENERATED by scripts/sync-shopify.mjs from Shopify metaobjects — do not hand-edit.
export const SITE_CONTENT: Record<string, any> | null = {
  "promos": [
    {
      "heading": "Stories that stay with you",
      "lead": "Discover the magic of Udaipur in",
      "book": "parth-the-promise",
      "note": "A novel · Book 1 of the Duology",
      "cta": "Buy now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1474932430478-367dbb6832c1.jpg?v=1791112582"
    },
    {
      "heading": "Exam season, sorted",
      "lead": "The prep book every aspirant keeps close",
      "book": "quantitative-aptitude",
      "note": "SSC · Banking · Railway",
      "cta": "Shop now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1497633762265-9d179a990aa6.jpg?v=1791112582"
    },
    {
      "heading": "Hindi sahitya, timeless",
      "lead": "Premchand's masterpiece, for every shelf",
      "book": "godan",
      "note": "Classic Hindi literature",
      "cta": "Shop now",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1526243741027-444d633d7365.jpg?v=1791112582"
    }
  ],
  "categories": [
    {
      "slug": "fiction",
      "label": "Fiction",
      "sub": "Stories",
      "icon": "",
      "href": "/category/fiction"
    },
    {
      "slug": "mystery-thriller",
      "label": "Mystery & Thriller",
      "sub": "Page-turners",
      "icon": "",
      "href": "/category/mystery-thriller"
    },
    {
      "slug": "self-help",
      "label": "Self Help",
      "sub": "Become more",
      "icon": "",
      "href": "/category/self-help"
    },
    {
      "slug": "hindi-literature",
      "label": "Hindi Literature",
      "sub": "साहित्य",
      "icon": "",
      "href": "/category/hindi-literature"
    },
    {
      "slug": "english-literature",
      "label": "English Literature",
      "sub": "Classics",
      "icon": "",
      "href": "/category/english-literature"
    },
    {
      "slug": "biography-history",
      "label": "Biography & History",
      "sub": "Real lives",
      "icon": "",
      "href": "/category/biography-history"
    },
    {
      "slug": "children",
      "label": "Children",
      "sub": "Young readers",
      "icon": "",
      "href": "/category/children"
    },
    {
      "slug": "education-exams",
      "label": "Education & Exams",
      "sub": "Prep",
      "icon": "",
      "href": "/category/education-exams"
    },
    {
      "slug": "maths-science",
      "label": "Maths & Science",
      "sub": "Concepts",
      "icon": "",
      "href": "/category/maths-science"
    }
  ],
  "moods": [
    {
      "slug": "feel",
      "label": "Feel",
      "sub": "Emotional",
      "icon": "",
      "href": "/mood/feel"
    },
    {
      "slug": "thrill",
      "label": "Thrill",
      "sub": "Mystery & Thriller",
      "icon": "",
      "href": "/mood/thrill"
    },
    {
      "slug": "learn",
      "label": "Learn",
      "sub": "Knowledge",
      "icon": "",
      "href": "/mood/learn"
    },
    {
      "slug": "reflect",
      "label": "Reflect",
      "sub": "Spiritual",
      "icon": "",
      "href": "/mood/reflect"
    },
    {
      "slug": "love",
      "label": "Love",
      "sub": "Romance",
      "icon": "",
      "href": "/mood/love"
    },
    {
      "slug": "grow",
      "label": "Grow",
      "sub": "Self-help",
      "icon": "",
      "href": "/mood/grow"
    },
    {
      "slug": "escape",
      "label": "Escape",
      "sub": "Fiction",
      "icon": "",
      "href": "/mood/escape"
    },
    {
      "slug": "light",
      "label": "Light",
      "sub": "Easy Reads",
      "icon": "",
      "href": "/mood/light"
    }
  ],
  "exams": [
    {
      "slug": "jee",
      "label": "JEE",
      "sub": "Engineering",
      "icon": "",
      "href": "/exam/jee"
    },
    {
      "slug": "neet",
      "label": "NEET",
      "sub": "Medical",
      "icon": "",
      "href": "/exam/neet"
    },
    {
      "slug": "upsc",
      "label": "UPSC",
      "sub": "Civil Services",
      "icon": "",
      "href": "/exam/upsc"
    },
    {
      "slug": "ssc",
      "label": "SSC",
      "sub": "Staff Selection",
      "icon": "",
      "href": "/exam/ssc"
    },
    {
      "slug": "banking",
      "label": "Banking",
      "sub": "IBPS • SBI",
      "icon": "",
      "href": "/exam/banking"
    },
    {
      "slug": "railway",
      "label": "Railway",
      "sub": "RRB • NTPC",
      "icon": "",
      "href": "/exam/railway"
    },
    {
      "slug": "cuet",
      "label": "CUET",
      "sub": "University",
      "icon": "",
      "href": "/exam/cuet"
    },
    {
      "slug": "cat",
      "label": "CAT",
      "sub": "MBA",
      "icon": "",
      "href": "/exam/cat"
    },
    {
      "slug": "gate",
      "label": "GATE",
      "sub": "M.Tech",
      "icon": "",
      "href": "/exam/gate"
    },
    {
      "slug": "school",
      "label": "School",
      "sub": "Class 1–12",
      "icon": "",
      "href": "/exam/school"
    },
    {
      "slug": "college",
      "label": "College",
      "sub": "UG • PG",
      "icon": "",
      "href": "/exam/college"
    },
    {
      "slug": "maths-science",
      "label": "Maths & Science",
      "sub": "Concepts",
      "icon": "",
      "href": "/exam/maths-science"
    }
  ],
  "budgets": [
    {
      "slug": "under-199",
      "label": "Under ₹199",
      "max": 199
    },
    {
      "slug": "under-299",
      "label": "Under ₹299",
      "max": 299
    },
    {
      "slug": "under-499",
      "label": "Under ₹499",
      "max": 499
    },
    {
      "slug": "under-999",
      "label": "Under ₹999",
      "max": 999
    }
  ],
  "giftBoxes": [
    {
      "slug": "book-lover-box",
      "name": "Book Lover Box",
      "items": [
        "1 book of your choice",
        "1 bookmark",
        "1 greeting card"
      ],
      "price": 599,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1512909006721-3d6018887383.jpg?v=1791112582"
    },
    {
      "slug": "birthday-book-box",
      "name": "Birthday Book Box",
      "items": [
        "1 book",
        "1 art / craft item",
        "1 greeting card"
      ],
      "price": 699,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1513885535751-8b9238bd345a.jpg?v=1791112582"
    },
    {
      "slug": "best-friend-box",
      "name": "Best Friend Box",
      "items": [
        "1 book",
        "1 bookmark",
        "1 small gift item"
      ],
      "price": 699,
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1544947950-fa07a98d237f.jpg?v=1791112582"
    }
  ],
  "stores": [
    {
      "slug": "abc-bookstore",
      "name": "ABC Bookstore",
      "location": "Johari Bazaar, Jaipur",
      "about": "A family-run bookstore serving Jaipur's readers since 1998. Strong in exam prep, Hindi literature and children's books.",
      "phone": "+91-98290-00000",
      "tag": "store:abc-bookstore",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1481627834876-b7833e8f5570.jpg?v=1791112582"
    },
    {
      "slug": "kitab-ghar",
      "name": "Kitab Ghar",
      "location": "Nai Sarak, Delhi",
      "about": "Old Delhi's beloved book lane veteran. Curated fiction, biographies and classics at honest prices.",
      "phone": "+91-98110-00000",
      "tag": "store:kitab-ghar",
      "photo": "https://cdn.shopify.com/s/files/1/1003/3237/2257/files/photo-1521587760476-6c12a4b040da.jpg?v=1791112582"
    }
  ],
  "home": {
    "handle": "homepage",
    "announcement_1": "Free shipping on orders above ₹499",
    "announcement_2": "100% original books",
    "announcement_3": "Verified physical bookstores",
    "show_book_of_day": "true",
    "show_budget": "true",
    "show_categories": "true",
    "show_exams": "true",
    "show_find_book": "true",
    "show_gift_boxes": "true",
    "show_moods": "true",
    "show_new_arrivals": "true",
    "show_reviews": "true",
    "show_slider": "true",
    "show_trending": "true"
  }
};
